### ISSUE TITLE
Split Atmos between Lossy and Lossless

### ISSUE THREAD

**Issue by Fringe09** [TRaSH-/Tutorials-FAQ#11]
I suggest splitting Atmos to Lossy and Lossless. Here is what I use:

TrueHD Atmos (lossless)
`truehd.*atmos|atmos.*truehd`

DDP 5.1 Atmos (lossy)
`\bDDP5.1\b.*atmos|atmos.*\bDDP5.1\b`

I added `|` just in case the title doesn't follow the correct format.

**Comment by TRaSH-** [comment]
Not sure if I'm going to split it but I will add them tomorrow perhaps.
But I noticed you only use 5.1 for lossy. What if there is a 7.1 ?
Or does that not exist ?

**Comment by Fringe09** [comment]
I believe Dolby Digital Plus doesn’t go beyond 5.1.

**Comment by TRaSH-** [comment]
Did some research and asking,
Got some big help from @rg9400.
When I get home tomorrow from work they will be added and a few others.
And a edited version from yours for better matching.

**Comment by TRaSH-** [comment]
should be added in the new and updated guide
