### ISSUE TITLE
Remote Path Mappings explained for Radarr (v3)

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Tutorials-FAQ#13]
Need to create; these may also be covered under the [new wiki](https://github.com/Servarr/Wiki) and may no longer be necessary?

**Comment by TRaSH-** [comment]
the one in the wiki is the one i made for V0.2
Need to fake a wrong path to get the new screenshots,
next weekend perhaps earlier i will first do the short explanation on how the CF works with the scores
