### ISSUE TITLE
RadarrV3 EVO Except WEB-DL

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Tutorials-FAQ#15]
https://github.com/TRaSH-/Tutorials-FAQ/blob/master/RadarrV3/Collection-of-Custom-Formats-for-RadarrV3.md#evo-except-web-dl

Needs to be the same points (but positive) that is set for the low quality groups or remove EVO from BLOCK4

BLOCK4 prevents EVO WEB-DL from DLing

**Comment by TRaSH-** [comment]
Fixed it the following way,
https://github.com/TRaSH-/Guides/blob/master/RadarrV3/Collection-of-Custom-Formats-for-RadarrV3.md#note-2
being when you add it to the blocks it will block all of them and not only the non web-dl
