### ISSUE TITLE
Sonarr Release profile prefers Season packs

### ISSUE THREAD

**Issue by nameproof** [TRaSH-/Tutorials-FAQ#2]
Thanks for this awesome profile!

I'd like to know what the intention of this one is: `\.S\d+\.(?!E\d+\.)`

For me it causes issues because it prefers Season packs over regular episodes which I don't want. Is this intentional or a side effect? 

Here's an example: 

> The.Last.Dance.S01.1080p.NF.WEB-DL.DDP5.1.x264-NTb
> The.Last.Dance.S01E10.Episode.X.1080p.NF.WEB-DL.DDP5.1.x264-NTb

Here it matches `.S01.` of the first example. 
It does not match `.S01E10.` of the second example

**Comment by christronyxyocum** [comment]
Ok, well, it's doing what it's designed to do, prefer season packs. If you do not prefer it grab the full season packs, then remove it from your release profile.

**Comment by nameproof** [comment]
That's all I wanted to know, what the intention was. (I thought it was something else because it's not very common to want that AFAIK). Thanks!

**Comment by TRaSH-** [comment]
Added it to optional with a remark to it.
https://github.com/TRaSH-/Tutorials-FAQ/commit/3acb71139b8888c2069fcaa98b0b34d085a1c369
