### ISSUE TITLE
[Suggestions] Add 10Bit for Radarr v3

### ISSUE THREAD

**Issue by RandomNinjaAtk** [TRaSH-/Tutorials-FAQ#21]
Add json template for h265 10bit

**Comment by TRaSH-** [comment]
Being you already prefer x265 you could just use the x265 with the HDR CF.
And give them like a score of 10 each.
This way if you get a x265 it will get a score of 10 but if it has both it gets 20.
If it doesn't show HDR I will need a few filename examples so I can do a few test.
You could also pm on discord if you don't want to share them here

**Comment by RandomNinjaAtk** [comment]
10bit does not equal HDR. One release type that is common is 10bit h265 bluray rips. Which would not qualify as HDR.

**Comment by TRaSH-** [comment]
Added: https://github.com/TRaSH-/Tutorials-FAQ/commit/ebbc87ef146373f61b32ea53ecdd81b03a38eb9a
