### ISSUE TITLE
Sonarr-Release-Profile-RegEx

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Tutorials-FAQ#22]
recommend splitting into 2 groups
1 that should be included in renaming (i.e. sources) to prevent loops
and 1 that is not to be included in renaming to prevent garbage naming
assumption: group is included in ones naming schema

**Comment by TRaSH-** [comment]
split what up in to 2 groups ?
the release profile of sonarr doesn't do anything with the renaming it only prefers the P2P releases over the scene releases

**Comment by bakerboy448** [comment]
For the non-groups (I.e sources)  NF, AMZN, etc. are not stored in the file name (typically)
If you enabled preferred words with them all in one you get double group names in your file naming. When using group + preferred words.


If you don’t use preferred words a perpetual upgrade loop occurs due to AMZN or ~ being constantly re-found

**Comment by bakerboy448** [comment]
![89D3ECB0-B5BA-41E3-9F9B-5D3ABF4668C9](https://user-images.githubusercontent.com/55419169/94366930-d9932a80-00a0-11eb-8a66-befded50bcf8.png)


Top turn on preferred words in renaming

Bottom that should be off

Then add preferred words to renaming schema

**Comment by TRaSH-** [comment]
are you sure that happens ?
sonarr doesn't have dynamic custom formats,
and it keeps the scene/release name in the database to my knowledge.
I use this setup on several other installs and never had that happen what you described.
if it does then it kinda sucks for sure.
but splitting it up would probably mean a complete recalculation of the scores.
being that amzn.web-dl are of a higher quality then the itunes web-dl and this won't be calculated anymore if you leave it out.

**Comment by bakerboy448** [comment]
It was happening; it appears it only compares the existing file based on file name.

Your hunch is correct though as when I did a rename after adding the sources as preferred words and to the file name it correctly updated

The scores still work as intended, I think.

1 set for sources w/ scoring w/ renaming 
1 set for groups & repacks etc

**Comment by TRaSH-** [comment]
but if you add them separate what changes ?
that it doesn't happen ?
you could pm me on discord if that's easier

**Comment by bakerboy448** [comment]
If you add them separate you can then enable that bundle in preferred words rename and not get double group names in the file if you enable preferred words rename  with it all in one.

Let’s hash this out on discord and circle back to git later

**Comment by TRaSH-** [comment]
when i find the time tomorrow i will change and update it.

**Comment by TRaSH-** [comment]
Fixed
