### ISSUE TITLE
WEB-DL / WEBRip matching

### ISSUE THREAD

**Issue by diego-ch** [TRaSH-/Tutorials-FAQ#23]
wouldn't it be `(name).?web.?(dl|rip)` to match on both radarr and sonarr?
they don't get tagged here with just `(name).?web.?dl`

example:
```
Some.Movie.2020.1080p.AMZN.WEBRip.DDP5.1.Atmos.x264-NTG
Some.Show.S01E01.1080p.AMZN.WEBRip.DDP5.1.x264-NTG
```

**Comment by TRaSH-** [comment]
The Sonarr release profile and Radarr custom format are based on original release name, not on renamed, retagged releases from other indexers.
Never understood why they do that in the first place.

**Comment by diego-ch** [comment]
oh so webrip is just a renaming that other indexers do?

**Comment by TRaSH-** [comment]
98% of the time yes.
