### ISSUE TITLE
[Suggestions] Potential new groups

### ISSUE THREAD

**Issue by christronyxyocum** [TRaSH-/Tutorials-FAQ#3]
Have some new potential groups to be added to the Sonarr v3 Release Profile you have:

https://sharex.tronflix.app/zORI8/PaPiJOJe09.png

https://sharex.tronflix.app/zORI8/fIBuveGI64.png

https://sharex.tronflix.app/zORI8/deJiLuYU99.png

**Comment by TRaSH-** [comment]
Link 2 screenshot doesn't work it gives a 404
Rest has been added and updated.
https://github.com/TRaSH-/Tutorials-FAQ/commit/3acb71139b8888c2069fcaa98b0b34d085a1c369
