### ISSUE TITLE
Optional season pack regex checks explicitly for '.' - should use word boundary

### ISSUE THREAD

**Issue by esran** [TRaSH-/Tutorials-FAQ#7]
The optional season pack regex `/\.S\d+\.(?!E\d+\.)/i` is explicitly looking for `.` separators. I found this resulted in it favouring one source of another that use whitespace separators instead. Suggest changing it to use word boundaries instead:

`/\bS\d+\b(?!E\d+\b)/i`

**Comment by TRaSH-** [comment]
Got a example for me so I can test it.
Keep in mind it's made to prefer P2P over scene.

**Comment by esran** [comment]
Hmm, not sure about the P2P vs scene difference.

```
Some.Show.S02.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG
Some Show S02 1080p AMZN WEB-DL DDP5 1 H 264-NTG
```

Two different trackers. The first one matches the original regex whilst the second doesn't. They both match using the suggested regex.

**Comment by TRaSH-** [comment]
I'll take a look at it this weekend.
To be honest the regex was actually made to catch something else.
Later we discovered that it actually works to catch a season pack.

**Comment by TRaSH-** [comment]
https://github.com/TRaSH-/Tutorials-FAQ/commit/5ec28d6943845df31961263aac73140c59e71d09
thnx
